
version: '3.8'
services:
    backend:
        build:
            context: ./server
        image: newguy/stock-analyzer_backend
        domainname: stock-analyzer
        ports:
            - "5000:5000"
        # restart: always
        # volumes:
        #     - ./server:/code
        deploy:
            resources:
                limits:
                    cpus: '2'
                    memory: 4G

    frontend:
        build:
            context: ./client
        image: newguy/stock-analyzer_frontend
        domainname: stock-analyzer
        ports:
            - "80:80"
        depends_on:
            - backend
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 4G
