
version: '3.8'
services:
    backend:
        build: server
        ports:
            - "8080:8080"
    frontend:
        build: client
        ports:
            - "80:80"
        depends_on:
          - backend
